apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-12-14T19:04:02Z"
  name: cartservice
  namespace: onlineboutique
  resourceVersion: "26197850"
  uid: 820122e5-172c-4c2a-bf08-76a748b7ffc9
spec:
  clusterIP: 10.112.14.88
  clusterIPs:
  - 10.112.14.88
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    app: cartservice
  sessionAffinity: None
  type: ClusterIP
