apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    config.k8s.io/owning-inventory: onlineboutique_repo-sync
    config.kubernetes.io/origin: |
      path: kustomize/base/cartservice.yaml
      repo: https://github.com/GoogleCloudPlatform/microservices-demo
      ref: main
    configmanagement.gke.io/cluster-name: asm-acm-tutorial
    configmanagement.gke.io/managed: enabled
    configmanagement.gke.io/source-path: asm-acm-tutorial/online-boutique/deployments/v1_service_cartservice.yaml
    configmanagement.gke.io/token: 1fbab5c90af9029b26451fec92e9900d8db23aee
    configsync.gke.io/declared-fields: '{"f:metadata":{"f:annotations":{"f:config.kubernetes.io/origin":{}},"f:labels":{}},"f:spec":{"f:ports":{"k:{\"port\":7070,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:type":{}}}'
    configsync.gke.io/git-context: '{"repo":"https://github.com/GoogleCloudPlatform/anthos-config-management-samples","branch":"main","rev":"HEAD"}'
    configsync.gke.io/manager: onlineboutique
    configsync.gke.io/resource-id: _service_onlineboutique_cartservice
  creationTimestamp: "2022-12-14T19:04:02Z"
  labels:
    app.kubernetes.io/managed-by: configmanagement.gke.io
    configsync.gke.io/declared-version: v1
  name: cartservice
  namespace: onlineboutique
  resourceVersion: "26197850"
  uid: 820122e5-172c-4c2a-bf08-76a748b7ffc9
spec:
  clusterIP: 10.112.14.88
  clusterIPs:
  - 10.112.14.88
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    app: cartservice
  sessionAffinity: None
  type: ClusterIP
