apiVersion: anthos.cloud.google.com/v1beta1
kind: CanonicalService
metadata:
  creationTimestamp: "2022-12-14T19:04:10Z"
  generation: 1
  name: frontend
  namespace: onlineboutique
  resourceVersion: "673234"
  uid: 2c85009e-31a8-4207-bbc3-021b29287bab
spec: {}
