apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-12-14T19:04:02Z"
  name: adservice
  namespace: onlineboutique
  resourceVersion: "26197849"
  uid: 47fe66a7-4cc3-43ce-8efc-33af3d407b8b
spec:
  clusterIP: 10.112.6.19
  clusterIPs:
  - 10.112.6.19
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 9555
    protocol: TCP
    targetPort: 9555
  selector:
    app: adservice
  sessionAffinity: None
  type: ClusterIP
