apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    config.k8s.io/owning-inventory: onlineboutique_repo-sync
    config.kubernetes.io/origin: |
      path: kustomize/base/adservice.yaml
      repo: https://github.com/GoogleCloudPlatform/microservices-demo
      ref: main
    configmanagement.gke.io/cluster-name: asm-acm-tutorial
    configmanagement.gke.io/managed: enabled
    configmanagement.gke.io/source-path: asm-acm-tutorial/online-boutique/deployments/v1_service_adservice.yaml
    configmanagement.gke.io/token: 1fbab5c90af9029b26451fec92e9900d8db23aee
    configsync.gke.io/declared-fields: '{"f:metadata":{"f:annotations":{"f:config.kubernetes.io/origin":{}},"f:labels":{}},"f:spec":{"f:ports":{"k:{\"port\":9555,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:type":{}}}'
    configsync.gke.io/git-context: '{"repo":"https://github.com/GoogleCloudPlatform/anthos-config-management-samples","branch":"main","rev":"HEAD"}'
    configsync.gke.io/manager: onlineboutique
    configsync.gke.io/resource-id: _service_onlineboutique_adservice
  creationTimestamp: "2022-12-14T19:04:02Z"
  labels:
    app.kubernetes.io/managed-by: configmanagement.gke.io
    configsync.gke.io/declared-version: v1
  name: adservice
  namespace: onlineboutique
  resourceVersion: "26197849"
  uid: 47fe66a7-4cc3-43ce-8efc-33af3d407b8b
spec:
  clusterIP: 10.112.6.19
  clusterIPs:
  - 10.112.6.19
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 9555
    protocol: TCP
    targetPort: 9555
  selector:
    app: adservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
