apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: onlineboutique
spec:
  clusterIP: 10.8.0.3
  clusterIPs:
  - 10.8.0.3
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
